#!/usr/bin/env bash
# Regenerate layer/src/shaders/passthrough_spv.h from the built-in .vert/.frag/.comp.
#
# The generated header is committed, so an ordinary build needs no shader compiler. This mirrors how
# the Windows app ships its shaders as generated headers -- the difference being SPIR-V rather than
# DXBC, which is the whole point of the port.
set -euo pipefail
cd "$(dirname "$0")/.."

GLSLANG="${GLSLANG:-$(command -v glslangValidator || command -v glslang || true)}"
if [ -z "$GLSLANG" ]; then
    echo "glslangValidator not found (set GLSLANG=/path/to/it)" >&2
    exit 1
fi

src=layer/src/shaders
out="$src/passthrough_spv.h"
tmpv="$(mktemp -t passthrough.XXXXXX.vert.spv)"
tmpf="$(mktemp -t passthrough.XXXXXX.frag.spv)"
tmpc="$(mktemp -t writeback.XXXXXX.comp.spv)"
trap 'rm -f "$tmpv" "$tmpf" "$tmpc"' EXIT

"$GLSLANG" -V "$src/passthrough.vert" -o "$tmpv" >/dev/null
"$GLSLANG" -V "$src/passthrough.frag" -o "$tmpf" >/dev/null
"$GLSLANG" -V "$src/writeback.comp" -o "$tmpc" >/dev/null

emit_array() { # emit_array <spv> <array-name>
    echo "static const uint32_t $2[] = {"
    od -An -tu4 -v "$1" | tr -s ' ' '\n' | grep -v '^$' | \
        awk '{printf "%s,", $0; if (++n % 10 == 0) printf "\n"} END {printf "\n"}'
    echo "};"
    echo "static const size_t ${2}Len = sizeof($2) / sizeof($2[0]);"
    echo
}

{
    echo "// Generated by tools/gen_builtin_spv.sh from passthrough.vert, passthrough.frag and"
    echo "// writeback.comp."
    echo "// Do not edit; edit the GLSL beside it and re-run the script."
    echo "#pragma once"
    echo "#include <cstddef>"
    echo "#include <cstdint>"
    echo
    echo "namespace shaderglass {"
    echo
    emit_array "$tmpv" kPassthroughVertSpv
    emit_array "$tmpf" kPassthroughFragSpv
    emit_array "$tmpc" kWritebackCompSpv
    echo "}  // namespace shaderglass"
} > "$out"

echo "wrote $out (vert $(wc -c < "$tmpv"), frag $(wc -c < "$tmpf"), comp $(wc -c < "$tmpc") bytes SPIR-V)"
